create table if not exists users(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    user_name varchar(100) unique,
    time_registration timestamp without time zone,
    status integer -- online=1/offline=0
);

create table if not exists servers(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    server_name varchar(100) unique,
    user_create integer references users(id),
    time_registration timestamp without time zone
);

create table if not exists channels(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    channel_name varchar(100),
    type_channel varchar(100),
    server_id integer references servers(id)
);

create table if not exists massages_channel(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    text varchar(512),
    time_dispatch timestamp without time zone
    sender integer references users(id),
    channel_id integer references channels(id)
);

create table if not exists voicechats(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    voicechat_name varchar(255),
    server_id integer references servers(id)
);

create table if not exists members_voicechat(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    member integer references users(id),
    voicechat_id integer references voicechats(id),
    time_connect timestamp without time zone
);


create table if not exists roles(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    role_name varchar(100),
    right varchar(100) -- права_роли
);

create table if not exists members_role(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    member integer references users(id),
    server_id integer references channels(id),
    role integer references roles(id);
);


