drop table if exists USERS CASCADE;
drop table if exists ITEMS CASCADE;

CREATE TABLE IF NOT exists USERS (
    id integer generated by default as identity PRIMARY KEY,
    name varchar(255) UNIQUE ,
    email varchar(255)
)

CREATE TABLE IF NOT EXISTS ITEMS(
    id integer generated by default as identity PRIMARY KEY,
    name varchar(255),
    description varchar(255),
    available boolean,
)

